### PR TITLE
services_cli: Fix list command wrongly showing root user as owner

### LINKED ISSUE #287: `brew services` returns incorrect user info
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

While helping to answer https://github.com/Homebrew/discussions/discussions/241, I happened to run `brew services` as both myself and root. To my surprise, the output of both commands differed in the _User_ column.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ sudo brew services
Name          Status  User Plist
daemontools   stopped      
dnsmasq       stopped      
httpd         stopped      
isync         stopped      
jack          stopped      
mariadb@10.3  stopped      
nginx         stopped      
openvpn       stopped      
php           started root /Users/aho/Library/LaunchAgents/homebrew.mxcl.php.plist
postgresql    started root /Users/aho/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
postgresql@11 stopped      
postgresql@12 stopped      
redis         stopped      
stunnel       stopped      
supervisor    stopped      
unbound       stopped      
</pre>
Wait, what? I was sure I started php and postgresql as NOT-root!
<pre>
$ brew services
Name          Status  User Plist
daemontools   stopped      
dnsmasq       stopped      
httpd         stopped      
isync         stopped      
jack          stopped      
mariadb@10.3  stopped      
nginx         stopped      
openvpn       stopped      
php           started aho  /Users/aho/Library/LaunchAgents/homebrew.mxcl.php.plist
postgresql    started aho  /Users/aho/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
postgresql@11 stopped      
postgresql@12 stopped      
redis         stopped      
stunnel       stopped      
supervisor    stopped      
unbound       stopped        
</pre>
Curiouser and curiouser...
<pre>
$ ps -ef | fgrep php
  501   602     1   0 22Nov20 ??         1:07.45 /usr/local/opt/php/sbin/php-fpm --nodaemonize
  501  1307   602   0 22Nov20 ??         0:00.15 /usr/local/opt/php/sbin/php-fpm --nodaemonize
  501  1308   602   0 22Nov20 ??         0:00.07 /usr/local/opt/php/sbin/php-fpm --nodaemonize
  501 64514 37527   0 11:16AM ttys004    0:00.01 ggrep -F --color=auto php
</pre>
My uid on this box is 501, so the correct user is running php...
<pre>
$ sudo brew services stop php
Error: Service `php` is started as `aho`. Try:
  brew services stop php
</pre>
...and `brew services` knows it too.
</details>

## What you expected to happen

I expected the output of both commands to be identical, and listing me as the user running both active services.

## Step-by-step reproduction instructions (by running `brew` commands)

```
# With at least one service started...
brew services
sudo brew services
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.6.0-180-g83b774d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 83b774d61fd60fd707dfb1ed20abccef2b02646b
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b7f1babd02b37ad8243973a8867439c8d3f2cc1b
Core tap last commit: 16 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.6.0_51-b11-457
macOS: 10.15.6-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  csv-fix
  encfs
  es
  ext2fuse
  json11
  ntfs-3g
  sshfs

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libpgtcl.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  lua@5.1
  xz
  libgcrypt
  moreutils
  gcc@8
  gcc@7
  neomutt
  node
  lzo

</pre>

### PR DESCRIPTION
**Pull request by issyl0**
- When running `brew services` with a couple of services started as a normal user, and one service started as root, this was the output:

```
➜ brew services
Name       Status  User   Plist
mosquitto  started issyl0 /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.mosquitto.plist
postgresql started   issyl0 /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
vault      error   root /Library/LaunchDaemons/homebrew.mxcl.vault.plist
```

- When running `sudo brew services` with the same combination of services, this was the output:

```
➜ sudo brew services
Password:
Name       Status  User Plist
mosquitto  started root /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.mosquitto.plist
postgresql started root /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
vault      error   root /Library/LaunchDaemons/homebrew.mxcl.vault.plist
```

- That is, the `User` column always showed `root` for all started services. That's because the `started?(as: :user)` conditional wrongly used the user invoking the `[sudo] brew services` command as the owning user for that process.

- This change fixes that by parsing the `user_path` for just the `started?(as: :user)` part of the `if` condition, and getting the username out of it.

- Fixes #287.

### CODE REVIEW

**Comment by issyl0** [comment]
Force-pushed to appease RuboCop.

File: lib/services_cli.rb [hunk 1]
```diff
@@ -38,6 +38,10 @@ def user_path
       Pathname.new("#{ENV["HOME"]}/Library/LaunchAgents")
     end
 
+    def user_from_standard_plist_path
+      ServicesCli.user_path.to_path.match(%r{Users/(\w+)})[1]
```
Comment (MikeMcQuaid) [inline lib/services_cli.rb:42]: Perhaps this could be simplified to just use `ENV["HOME"]` directly?

**Review by MikeMcQuaid — COMMENTED** [review]
Nice work here! I wonder if we could be more accurate still by using something like `/bin/ps -o user -p ... -p ...` with the `Service#pid` to get the actual `user` for these processes?

File: lib/services_cli.rb (hunk 1 above)
Comment (issyl0) [reply lib/services_cli.rb]: Much simpler! I was too far into "but how does this work and why is it weird?" last night, clearly. 😄

**Comment by issyl0** [comment]
> I wonder if we could be more accurate still by using something like `/bin/ps -o user -p ... -p ...` with the Service#pid to get the actual user for these processes?

This approach would only show `started` processes with populated `User` data, because errored processes don't have PIDs.

```
mosquitto  started issyl0 /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.mosquitto.plist
postgresql error          /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
```

Also, getting user info through `ps`, `sudo brew services` would display no user information for processes that weren't started as root.

**Comment by MikeMcQuaid** [comment]
> This approach would only show `started` processes with populated `User` data, because errored processes don't have PIDs.

I think this would be ok! They could either not show the user at all or fall back to the existing logic?


> Also, getting user info through `ps`, `sudo brew services` would display no user information for processes that weren't started as root.

Can you explain this a bit more, I'm not sure I understand?

**Comment by issyl0** [comment]
@MikeMcQuaid The fallback to using `ENV["HOME"]` if no PIDs are found solves the "`sudo brew services` doesn't work" part of my previous comment.

**Comment by MikeMcQuaid** [comment]
Code makes sense to me as-is! Unfortunately it looks like CI is broken 😅

**Comment by issyl0** [comment]
The tests pass fine for me locally. I don't have enough permissions here to re-run CI to see if it was just a temporary blip.

**Comment by MikeMcQuaid** [comment]
@issyl0 Failed twice in a row here I'm afraid 😭

**Comment by issyl0** [comment]
@MikeMcQuaid 😭 I'll dig into it tonight!

**Comment by issyl0** [comment]
I've tested this branch on two separate MacBooks (one Catalina and one Big Sur) and I can't reproduce the `brew services start mysql` failures. I enabled GitHub Actions on my fork, and it fails with the same error message both on this branch and `master` ([link to `master` branch run](https://github.com/issyl0/homebrew-services/runs/1555739418#step:10:297)). So it must be an Actions hosted runners thing. 😕

**Comment by MikeMcQuaid** [comment]
@issyl0 Could try to bump the `sleep` or improve the debugging output on failure?

**Comment by MikeMcQuaid** [comment]
Nice fix and work here in general, thanks @issyl0!

**Comment by gromgit** [comment]
Thanks much, @issyl0! I just confirmed that it's working on my box.

**Comment by issyl0** [comment]
Hurray! 🎉
