### PR TITLE
fix: install service file specified by --file

### LINKED ISSUE #364: Custom plists are no longer installed in the LaunchDaemons/LaunchAgents directories
Greetings,

Sorry to bother you again about this, but an issue still remain after my last issue (#349) and I took way to much time to notice it. The PR that added the `--file` argument (#353) changed the installation behaviour of custom plist files. That change cause services to not start after a system reboot.

Normally, plist files (customs and regulars) would be installed in the `LaunchDaemons`/`LaunchAgents` directories. Now, custom plist files are installed in different directory. For example, custom mysql plist are installed in `/usr/local/opt/mysql/homebrew.mxcl.mysql.plist` instead of `/Users/USERNAME/Library/LaunchAgents/homebrew.mxcl.mysql.plist`.

Would it be possible to restore the previous behaviour to ensure that the services start after a system reboot? I would love to make a PR myself, but Ruby is not a language that I practice often enough. However, I do think the issue is around this line: https://github.com/Homebrew/homebrew-services/blob/master/lib/services_cli.rb#L237

Thanks!

### PR DESCRIPTION
**Pull request by SMillerDev**
Should fix #364

### CODE REVIEW

File: lib/services_cli.rb [hunk 1]
```diff
@@ -412,13 +413,17 @@ def service_load(service, enable:)
...
         odie "Formula `#{service.name}` has not implemented #plist, #service or installed a locatable service file"
       end
 
       temp = Tempfile.new(service.service_name)
-      temp << service.service_file.read
+      if file.blank?
+        temp << service.service_file.read
+      else
+        temp << file.read
+      end
```
Comment (MikeMcQuaid) [inline lib/services_cli.rb:426]:
```suggestion
      temp << if file.blank?
        service.service_file.read
      else
        file.read
      end
```

**Review by MikeMcQuaid — APPROVED** [review]
