### PR TITLE
Fixed error when starting service using OS X 10.11.5

### LINKED ISSUE #56: Unable to start services - "The UserName key is not supported for non-System services."
Since upgrading to OS X 10.11.5 I can no longer start services like httpd22.

`brew services start httpd22` results in `==> Successfully started ``httpd22`` (label: homebrew.mxcl.httpd22)` which is perfectly fine.

However, when inspecting the logs using `syslog -k Sender com.apple.xpc.launchd` I noticed the following entries:
```bash
May 27 09:48:22 name com.apple.xpc.launchd[1] (homebrew.mxcl.httpd22) <Error>: The UserName key is not supported for non-System services.
May 27 09:48:22 name com.apple.xpc.launchd[1] (homebrew.mxcl.httpd22[22553]) <Warning>: Service exited with abnormal code: 1
```

The `.plist`-file contains the section in question which was perfectly fine prior the update. Anyone experienced anything like that before?

### PR DESCRIPTION
**Pull request by daFish**
This applies the fix from #56 

Fixes #56

### CODE REVIEW

File: cmd/brew-services.rb [hunk 1]
```diff
@@ -466,17 +466,7 @@ def generate_plist(data = nil)
...
-      if data =~ %r{<key>UserName</key>}
-        # Replace existing UserName value with current user
-        data = data.gsub(%r{(<key>UserName</key>\s*<string>)[^<]*(</string>)}, '\1' + ServicesCli.user + '\2')
-      else
-        # Add UserName key and value to end of plist if it doesn't already exist
-        data = data.gsub(%r{(\s*</dict>\s*</plist>)}, "\n    <key>UserName</key>\n    <string>" + ServicesCli.user + "</string>\\1")
-      end
-    elsif data =~ %r{<key>UserName</key>}
-      # Always remove UserName key entirely if running as root
+    if data =~ %r{<key>UserName</key>}
```
Comment (MikeMcQuaid) [inline cmd/brew-services.rb]: Tiny tweak: a little comment saying something about always removing the UserName as it doesn't work on 10.11.5 would be 👍

**Comment by MikeMcQuaid** [comment]
Thanks @daFish!
